getgauge/gauge-js

.gitignore
package.json
scripts/install.js

To install plugin, run:
$ npm run pluginInstall
To create plugin package, run:
$ npm run package

Add package script and refactor install

---

README.md

Documenting the configuration options

---

README.md
skel/step_implementation.js
src/custom-message-registry.js
src/data-store-factory.js
src/executor.js
src/gauge-global.js
src/hook-registry.js
src/impl-loader.js
src/message-processor.js
src/refactor.js
src/step-registry.js
test/custom-message-registry-test.js
test/executor-test.js
test/gauge-global-test.js
test/hook-registry-test.js
test/message-processor-test.js
test/refactor-test.js
test/step-registry-test.js

Expose a single global `gauge{}` object.

---

src/gauge-global.js
src/static-loader.js
src/step-registry.js
test/message-processor-test.js
test/static-loader-test.js
test/step-registry-test.js

* stepRegistry holds the range of step instead of lineNumber

Adding step span in stepPositionResponse instead of lineNumber

---

src/test.js
test/test.js

Stacktrace from runners should contain relative paths in the stacktrace

Stacktrace should contain relative path #96

---

.jshintrc
src/gauge-global.js
src/gauge.js
src/message-processor.js
src/static-loader.js
src/step-registry.js
test/executor-test.js
test/gauge-global-test.js
test/message-processor-test.js
test/static-loader-test.js
test/step-registry-test.js

- Storing aliases in step registry.
- Sending aliases along with StepNameResponse.

Sending aliases with StepNameResponse, #933

---

src/impl-loader.js
src/message-processor.js
src/response-factory.js

* Return a list of implementation files based on the file pattern provided in config
* Append stub implementation code snippet to an implementation file

119 generate stub

---

package.json
src/refactor.js
src/string-util.js
test/refactor-test.js
test/string-util-test.js

refactoring parameters retains old positions and names, converts to camel case and filters invalid characters.

better refactoring support for paramters. #104

---

package-lock.json
src/tracker.js

tests were failing with a message if there is no dependencies https://github.com/getgauge/gauge/issues/1392

fixed issue of failing test in case of no dependencies

---

package-lock.json
package.json
test/file-util-test.js
test/lsp-server-test.js
test/message-processor-test.js

removed mock-fs dependency #179

179 mock fs

---

offline-package.json
package.json
scripts/install.js
src/gauge.js
src/message-processor.js

Added support to generate a Gauge JS runner with pure js GRPC implementation which can be installed offline.

Pure js grpc

---

.github/workflows/build.yml
package-lock.json
package.json
src/gauge-global.js

Before
gauge.step(...)
After
step(...)

Remove deprecated gauge global

---

js.json
package-lock.json
package.json

Signed-off-by: Dharmendra Singh <dharmenn@thoughtworks.com>

Bump up version to 2.3.11

---

js.json
package-lock.json
package.json
src/test.js

Fix stack trace choping #350

---

src/message-processor.js

Clearing data store post hook execution. #227

---

js.json
package-lock.json
package.json
src/test.js

Signed-off-by: NivedhaSenthil <nivedhasenthil@gmail.com>

#98 Error on arg length mismatch and timedout

---

js.json
package-lock.json
package.json

Bump version to 2.3.14

---

.github/workflows/build.yml
src/executor.js

- Avoid creating empty table object if value and table is not present
- Run lsp test on commit instead of master
Signed-off-by: NivedhaSenthil <nivedhasenthil@gmail.com>

Fix empty parameter and action

---

.github/workflows/release.yml

- hub comes pre installed in actions now
Signed-off-by: NivedhaSenthil <nivedhasenthil@gmail.com>

remove use of hub action

---

.github/workflows/build.yml

Use gauge setup repository action

---

.github/workflows/build.yml

Use released version of html report plugin

---

.github/workflows/release.yml

Replace deprecated set-env

---

js.json
package-lock.json
package.json

Bumping up version as a lot of libraries and security fixes were added since the last release.

Bump up version to 2.3.16

---

js.json
package-lock.json
package.json
src/file-util.js
test/lsp-server-test.js

- log when test fails while loading submodule
- updated klaw-sync to v6.0.0

klaws sync fix

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/release.yml
README.md
js.json
package-lock.json
package.json

Retrying release from #571 
Also upgrades dependencies to resolve security noise (requiring increase in minimum node version to 12, which was still EOL some time ago)

Fix build and re-try release

---

js.json
package-lock.json
package.json
src/table.js

Updated how the table entries function is checking if the callback function is an AsyncFunction

Correct how table entries function checks for async callbacks

---

package-lock.json
package.json

Revert "Bump @grpc/grpc-js from 1.9.5 to 1.9.7"
